<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="6">
            <File firstVisibleLine="458" xOffset="0" scrollWidth="849" startPos="12310" endPos="12315" selMode="0" lang="HTML" encoding="-1" filename="C:\inetpub\wwwroot\jquery\browser-module\index.html" backupFilePath="" originalFileLastModifTimestamp="1545621357" mapFirstVisibleDisplayLine="458" mapFirstVisibleDocLine="458" mapLastVisibleDocLine="511" mapNbLine="53" mapHigherPos="-1" mapWidth="316" mapHeight="159" mapKByteInDoc="16" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="105" xOffset="0" scrollWidth="1220" startPos="3705" endPos="3705" selMode="0" lang="CSS" encoding="-1" filename="C:\inetpub\wwwroot\jquery\browser-module\css\CSS.css" backupFilePath="" originalFileLastModifTimestamp="1545829003" mapFirstVisibleDisplayLine="108" mapFirstVisibleDocLine="108" mapLastVisibleDocLine="160" mapNbLine="52" mapHigherPos="-1" mapWidth="150" mapHeight="156" mapKByteInDoc="19" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="989" startPos="789" endPos="789" selMode="0" lang="JavaScript" encoding="-1" filename="C:\inetpub\wwwroot\jquery\browser-module\js\control\click.js" backupFilePath="" originalFileLastModifTimestamp="1546008077" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="53" mapNbLine="53" mapHigherPos="-1" mapWidth="316" mapHeight="159" mapKByteInDoc="18" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1015" startPos="770" endPos="770" selMode="0" lang="JavaScript" encoding="-1" filename="C:\inetpub\wwwroot\jquery\browser-module\js\control\control.js" backupFilePath="" originalFileLastModifTimestamp="1546004352" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="53" mapNbLine="53" mapHigherPos="-1" mapWidth="316" mapHeight="159" mapKByteInDoc="21" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="854" startPos="408" endPos="408" selMode="0" lang="JavaScript" encoding="-1" filename="C:\inetpub\wwwroot\jquery\browser-module\js\control\edit.js" backupFilePath="" originalFileLastModifTimestamp="1546004143" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="53" mapNbLine="53" mapHigherPos="-1" mapWidth="156" mapHeight="159" mapKByteInDoc="7" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="774" startPos="406" endPos="406" selMode="0" lang="JavaScript" encoding="-1" filename="C:\inetpub\wwwroot\jquery\browser-module\js\model\equip.js" backupFilePath="" originalFileLastModifTimestamp="1546004143" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="53" mapNbLine="53" mapHigherPos="-1" mapWidth="156" mapHeight="159" mapKByteInDoc="6" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="742" startPos="83" endPos="83" selMode="0" lang="JavaScript" encoding="-1" filename="C:\inetpub\wwwroot\jquery\browser-module\js\main.js" backupFilePath="" originalFileLastModifTimestamp="1546002253" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="53" mapNbLine="53" mapHigherPos="-1" mapWidth="319" mapHeight="159" mapKByteInDoc="0" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="928" startPos="977" endPos="977" selMode="0" lang="JavaScript" encoding="-1" filename="C:\inetpub\wwwroot\jquery\browser-module\js\model\menu.js" backupFilePath="" originalFileLastModifTimestamp="1546004453" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="52" mapNbLine="52" mapHigherPos="-1" mapWidth="156" mapHeight="156" mapKByteInDoc="16" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="834" startPos="115" endPos="115" selMode="0" lang="JavaScript" encoding="-1" filename="C:\inetpub\wwwroot\jquery\browser-module\js\model\model.js" backupFilePath="" originalFileLastModifTimestamp="1546004143" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="53" mapNbLine="53" mapHigherPos="-1" mapWidth="156" mapHeight="159" mapKByteInDoc="14" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="904" startPos="1172" endPos="1172" selMode="0" lang="JavaScript" encoding="-1" filename="C:\inetpub\wwwroot\jquery\browser-module\js\model\serv.js" backupFilePath="" originalFileLastModifTimestamp="1546004143" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="52" mapNbLine="52" mapHigherPos="-1" mapWidth="156" mapHeight="156" mapKByteInDoc="24" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="984" startPos="521" endPos="521" selMode="0" lang="JavaScript" encoding="-1" filename="C:\inetpub\wwwroot\jquery\browser-module\js\model\sort.js" backupFilePath="" originalFileLastModifTimestamp="1546004143" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="52" mapNbLine="52" mapHigherPos="-1" mapWidth="156" mapHeight="156" mapKByteInDoc="6" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="880" startPos="163" endPos="163" selMode="0" lang="JavaScript" encoding="-1" filename="C:\inetpub\wwwroot\jquery\browser-module\js\model\util.js" backupFilePath="" originalFileLastModifTimestamp="1546004143" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="53" mapNbLine="53" mapHigherPos="-1" mapWidth="156" mapHeight="159" mapKByteInDoc="26" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="809" startPos="663" endPos="663" selMode="0" lang="JavaScript" encoding="-1" filename="C:\inetpub\wwwroot\jquery\browser-module\js\view\view.js" backupFilePath="" originalFileLastModifTimestamp="1546004143" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="53" mapNbLine="53" mapHigherPos="-1" mapWidth="156" mapHeight="159" mapKByteInDoc="25" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="886" startPos="393" endPos="393" selMode="0" lang="JavaScript" encoding="-1" filename="C:\inetpub\wwwroot\jquery\browser-module\js\view\viewmenu.js" backupFilePath="" originalFileLastModifTimestamp="1546004143" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="53" mapNbLine="53" mapHigherPos="-1" mapWidth="156" mapHeight="159" mapKByteInDoc="16" mapWrapIndentMode="1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>
