| book  | CREATE TABLE `book` (
  `deleted` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `waitnum` double DEFAULT '1',
  `opdate` date DEFAULT NULL,
  `oproom` tinyint(2) DEFAULT NULL,
  `optime` varchar(10) NOT NULL DEFAULT '',
  `casenum` tinyint(2) DEFAULT NULL,
  `theatre` varchar(30) NOT NULL DEFAULT '',
  `staffname` varchar(50) NOT NULL DEFAULT '',
  `hn` varchar(10) NOT NULL DEFAULT '',
  `patient` varchar(255) NOT NULL DEFAULT '',
  `dob` date DEFAULT NULL,
  `gender` varchar(1) NOT NULL DEFAULT '',
  `diagnosis` varchar(1000) NOT NULL DEFAULT '',
  `treatment` varchar(1000) NOT NULL DEFAULT '',
  `admission` varchar(5000) NOT NULL DEFAULT '',
  `final` varchar(5000) NOT NULL DEFAULT '',
  `equipment` varchar(2000) NOT NULL DEFAULT '',
  `contact` varchar(1000) NOT NULL DEFAULT '',
  `admit` date DEFAULT NULL,
  `discharge` date DEFAULT NULL,
  `admitted` varchar(30) NOT NULL DEFAULT '',
  `operated` varchar(30) NOT NULL DEFAULT '',
  `doneday` date DEFAULT NULL,
  `doneby` varchar(30) NOT NULL DEFAULT '',
  `manner` varchar(30) NOT NULL DEFAULT '',
  `scale` varchar(30) NOT NULL DEFAULT '',
  `disease` varchar(255) NOT NULL DEFAULT '',
  `nonsurgical` varchar(50) NOT NULL DEFAULT '',
  `infection` varchar(30) NOT NULL DEFAULT '',
  `morbid` varchar(30) NOT NULL DEFAULT '',
  `dead` varchar(30) NOT NULL DEFAULT '',
  `qn` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `editor` varchar(10) NOT NULL DEFAULT '',
  PRIMARY KEY (`qn`),
  KEY `opdate` (`opdate`),
  KEY `hn` (`hn`)
) ENGINE=InnoDB AUTO_INCREMENT=2082 DEFAULT CHARSET=utf8 |
