| book  | CREATE TABLE `book` (
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  `waitnum` double DEFAULT '1',
  `opdate` date DEFAULT NULL,
  `oproom` tinyint(2) DEFAULT NULL,
  `optime` varchar(10) NOT NULL DEFAULT '',
  `casenum` tinyint(2) DEFAULT NULL,
  `theatre` varchar(255) NOT NULL DEFAULT '',
  `staffname` varchar(255) NOT NULL DEFAULT '',
  `hn` varchar(10) NOT NULL DEFAULT '',
  `patient` varchar(255) NOT NULL DEFAULT '',
  `dob` date DEFAULT NULL,
  `gender` varchar(1) NOT NULL DEFAULT '',
  `diagnosis` varchar(1000) NOT NULL DEFAULT '',
  `treatment` varchar(1000) NOT NULL DEFAULT '',
  `admission` varchar(5000) NOT NULL DEFAULT '',
  `final` varchar(5000) NOT NULL DEFAULT '',
  `equipment` varchar(2000) NOT NULL DEFAULT '',
  `contact` varchar(1000) NOT NULL DEFAULT '',
  `admit` date DEFAULT NULL,
  `discharge` date DEFAULT NULL,
  `doneday` date DEFAULT NULL,
  `admitted` enum('','Admit','Readmission') DEFAULT NULL,
  `operated` enum('','Operation','Reoperation') DEFAULT NULL,
  `manner` enum('','Elective','Emergency') DEFAULT NULL,
  `doneby` enum('','Staff','Resident') DEFAULT NULL,
  `scale` enum('','Major','Minor') DEFAULT NULL,
  `disease` enum('','Brain Tumor','Brain Vascular','CSF related','Trauma','Spine','etc.','Radiosurgery','Endovascular') DEFAULT NULL,
  `infection` enum('','Infection') DEFAULT NULL,
  `morbid` enum('','Morbidity') DEFAULT NULL,
  `dead` enum('','Dead') DEFAULT NULL,
  `qn` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `editor` varchar(10) NOT NULL DEFAULT '',
  PRIMARY KEY (`qn`),
  KEY `opdate` (`opdate`),
  KEY `hn` (`hn`)
) ENGINE=InnoDB AUTO_INCREMENT=1655 DEFAULT CHARSET=utf8 |
